CFLAGS=-za99 -oahnxs -ei -zp8 -0 -oe
CC=wcl

TARGETS=sample.app

src = $(wildcard *.c)
obj = $(src:.c=.o)

.PHONY: all clean
all: $(TARGETS)
clean:
	rm -f $(TARGETS) $(obj)

sample.app: sample.c
	$(CC) $(CFLAGS) -mc $< -fe=$@
	wdis sample.o -l=sample.s
	@du -b $@
